### ISSUE TITLE
Dynamically created JSON not supported 

### ISSUE THREAD

**Issue by sagar94** [softvar/json2html#14] opened 2015-12-30 17:29 UTC
The function doesn't provide favorable results on dynamically created json (values collected as json dump from mongodb)
But if the same json is printed in console and the static output is used in code it works exactly as it should.

This doesn't work
```python
response = db.reports.find({"MobileNo":No}) // mongo query returns cursor
aggregate = dumps(response) // dumps json
final['sample'] = aggregate
table = json2html.convert(json = final)
 ```

But if you copy the console output of aggregate and pass it a static string to the json2html.convert() it works perfectly
eg  `print aggregate`
> [{"eosinophils": "03", "mchc": "336", "hct": "333", "mch": "190", "_id": {"$oid": "567c385ac3ea3256121cb6f5"}, "rbc": "563"}, {"eosinophils": "03", "mchc": "336", "hct": "333", "mch": "190", "_id": {"$oid": "567c3a5ac3ea3256cb1ff2a5"}, "rbc": "563"}]

```python
response = db.reports.find({"MobileNo":No}) // mongo query returns cursor
aggregate = dumps(mongo_query_response)
final['sample'] = [{"eosinophils": "03", "mchc": "336", "hct": "333", "mch": "190", "_id": {"$oid": "567c385ac3ea3256121cb6f5"}, "rbc": "563"}, {"eosinophils": "03", "mchc": "336", "hct": "333", "mch": "190", "_id": {"$oid": "567c3a5ac3ea3256cb1ff2a5"}, "rbc": "563"}]
table = json2html.convert(json = final)
 ```

**Comment by softvar** [comment] 2015-12-30 20:31
This seems weird,
Can you please check:

1. The data returned is valid JSON, no string.
2. Any errors you get while running the code.

Will have to debug once the cause is diagnosed.

**Comment by muellermichel** [comment] 2015-12-31 06:03
This is expected behavior. @sagar94, you are probably using `dumps` from the built-in json package (by using `from json import *`). `dumps` produces a JSON string representation for python data, i.e. it's the opposite of `loads` in many ways. What happens if you just call `json2html.convert(json = response)`?

**Comment by sagarspecter** [comment] 2016-01-04 11:32
@sagar94  I had same issue. @muellermichel `response` is a cursor and hence `json2html.convert(json = response)` also gives error. But I figured a way out with proper `loads` and `dumps` mechanisms for serialization. Now we get a valid json, which when passed to the `json2html.convert()` gave perfect results.
```python
aggregate = json.loads(json_util.dumps(response))
print "Here it is"
print aggregate
agg = {}
agg['sample'] = aggregate
table = json2html.convert(json = agg)```

**Comment by softvar** [comment] 2016-01-04 13:07
Glad to hear that @sagar94 
Closing the issue then :)

**Closed** 2016-01-04 13:07 UTC

**Comment by muellermichel** [comment] 2016-01-05 00:53
@sagar94 I'd actually be interested in the error thrown there.
@softvar I think as a design principle it might make sense for json2html to become absolutely bullet proof, i.e. just take whatever the user throws at it, create html from what it knows and ignore the rest. The user would never have to care about any error thrown, only check whether the result makes sense - which I suspect all users do. This would allow json2html to become useful as a last resort error handler for example (user program goes into an error state, just throw whatever we have into json2html and display it to user). I think it even might make sense to do a json.loads inside json2html if the top level object is a string (since a string alone can AFAIK never be a valid object itself). What do you think?
