### ISSUE TITLE
ImportError: No module named 'jsonconv'

### ISSUE THREAD

**Issue by MindMapMaker** [softvar/json2html#12] opened 2015-09-22 20:49 UTC
Just did a pip install json2html with no errors. However, when I did "from json2html import *" I got:
    from jsonconv import *
ImportError: No module named 'jsonconv'
Where can I get that module to install?
I am running Python 3.4
Perhaps with a little hint I could do the conversion.

Thanks. :)

**Comment by ba1dr** [comment] 2015-11-27 19:08
It seems this library is not python3-compatible.

Error was caused by this line in the \_\_init\_\_.py file:

    from jsonconv import *

While, instead, it should be:

    from .jsonconv import *

**Comment by randomInteger** [comment] 2016-06-07 21:53
ba1dr is correct, that change unbroke this for python 3.4.3 on my system.

**Comment by jacohend** [comment] 2016-12-07 01:52
Looks like it's available over python3-pip for some reason (which is kinda like advertising support for Python3 IMO). Could this be removed from pypi?

**Comment by muellermichel** [comment] 2016-12-29 06:48
This is related to my pull request and would be fixed after merging: https://github.com/softvar/json2html/pull/21

**Comment by softvar** [comment] 2016-12-29 19:04
This is done. #21 merged 😄 
Closing this now.

**Closed by softvar** 2016-12-29 19:04 UTC
